server:
#  servlet:
#    context-path: /100
  port: 8001

---
spring:
  jpa:
    show-sql: false
    database-platform: com.hottop.core.utils.database.Mysql57InnoDBDialectUtf8mb4
    hibernate:
      naming.implicit-strategy: com.hottop.core.utils.database.SimpleImplicitNamingStrategyImpl

---
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

---
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gbuyer?Unicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 5
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      min-evictable-idle-time-millis: 1800000
      min-idle: 5
    tomcat:
      max-active: 50
      max-wait: 60000

---
spring:
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000ms

---
redis:
  #最大空闲数
  maxIdle: 30
  maxTotal: 50
  maxWaitMillis: 2000
  hostname: 127.0.0.1
  port: 6379
  password: root
