server:
#  servlet:
#    context-path: /100
  port: 8001

base:
  host: hottop.com

---
spring:
  profiles:
    active: dev # prod, test, release

---
spring:
  jpa:
    show-sql: false
    database-platform: com.hottop.core.utils.database.Mysql57InnoDBDialectUtf8mb4
    hibernate:
      naming.implicit-strategy: com.hottop.core.utils.database.SimpleImplicitNamingStrategyImpl

---
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

---
ht:
  security:
    social:
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessesUrl: /social
      connectionTablePrefix: gb_

    browser:
      signUpUrl: /demo-signUp.html
      jwtExpireTime: 6000 #jwt 失效时间
      jwtRefreshTime: 12000 #刷新token失效时间,默认一周
    code:
      image:
        expireIn: 120
      sms:
        #短信验证码的长度
        length: 6
        #失效时间
        expireIn: 60
        #发送短信的签名
        currentCompanyName: 北京凡生易美科技有限公司


---
spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672